### ISSUE TITLE
great job done here!

### ISSUE THREAD

**Issue by Desdichado** [Jimbolino/laravel-model-builder#2]
Great job done here! This project is really needed!
If i find time over some day i'll try to help you out if you need help! 
Some other projects that i have found working (have been working) in similar direction:
in php: https://github.com/ftrotter/ORMBuild
in java: https://bitbucket.org/jordicabot/umltosql-umltophp-symfony-umltopython-django/src/9fd512d5d69e4648b028bae8caa149ab0f8bbc10/src/mdeServices/?at=master
Thought it might help if you get stuck :)

**Comment by Jimbolino** [comment]
thnx for the links
ftrotter/ORMBuild has a nice feature where you can "inject" code between the automatic generation, and the final file.
I might consider something like that in the future, but i want it to be more plug and play.
